### ISSUE TITLE
Remootio 2 restarts on HELLO message

### ISSUE THREAD

**Issue by DaveD-W** [remootio/remootio-api-client-node#1]
Hi,

It looks like there is an issue with the API that when a hello command is sent, the device restarts!

Found this out by using https://github.com/ronniepettersson/homebridge-remootio - by removing the hello command as a workaround, everything works as expected.

Example output from Homebridge: 
[11/22/2020, 11:10:01 PM] [Remootio] [Garage Door] Outgoing: HELLO
[11/22/2020, 11:10:01 PM] [Remootio] [Garage Door] Incoming:
{"event":{"cnt":0,"type":"Restart","state":"open","t100ms":6}}

Thanks,
Dave.

**Comment by remootio** [comment]
Hello Dave,

Thank you for reporting the issue. We have corrected the bug in the firmware causing this, and it will be out with the v2.22 firmware update soon
