### ISSUE TITLE
sendTrigger Duration support

### ISSUE THREAD

**Issue by lowefraser** [remootio/remootio-api-client-node#13]
I can't see that the node client supports setting the duration on the trigger as per v3 of the API?

**Comment by remootio** [comment]
@lowefraser Thanks for pointing this out.

I've added a separate set of functions that use the duration parameter as well:
The new version is also published on npm

 - `holdTriggerOutputActive(durationMins)` - Holds the control output which would be triggered by sendTrigger active for durationMins minutes
 - `holdTriggerSecondaryOutputActive(durationMins)` - Holds the control output which would be triggered by sendTriggerSecondary active for durationMins minutes
 - `holdOpenOutputActive(durationMins)` - Holds the control output which would be triggered by sendOpen active for durationMins minutes
 - `holdCloseOutputActive(durationMins)` - Holds the control output which would be triggered by sendClose active for durationMins minutes

**Comment by lowefraser** [comment]
Thank you
