### ISSUE TITLE
sendQuery don't work

### ISSUE THREAD

**Issue by sdomotica** [remootio/remootio-api-client-node#3]
I tried the test code

```
garagedoor1.on('authenticated',()=>{`
    console.log('garage door 1 session authenticated')
    console.log('garage door 1 pre quey')
    garagedoor1.sendQuery()
    console.log('garage door 1 post query')

})

```

No response only loop authentication

![immagine](https://user-images.githubusercontent.com/781294/112381596-0b511b00-8ceb-11eb-9f84-83907847e245.png)

2.25 Firmware

garagedoor1.sendTrigger()
 Works fine

Thks
Sandro

**Comment by remootio** [comment]
Hi Sandro,

Can you please post the full code you are using? 
I couldn't reproduce the issue
